### ISSUE TITLE
Vertical Cross Section not displaying proper values for Serafin files produced by Telemac v7p2

### ISSUE THREAD

**Issue by jamaa** [CNR-Engineering/PyTelTools#3]
Using a Serafin result file produced using Telemac v7p2: the Vertical Cross Section always displays only a single value (seemingly the initial value), see the screenshot. Also, when I select a different section, the x and y axis (elevation) are not adjusted to the new min-max values of that section. 
Other visualizations (Vertical Temporal Profile 3D) and processes (Write vtk) work fine and show that there are indeed values in the Serafin file.
The problem does not occur using Serafin result files produced by Telemac v6p1, so I'm not sure what the issue is. 
![pyteltools_section](https://user-images.githubusercontent.com/90166/32431853-5d550eae-c2d5-11e7-9b87-d1072672db9c.png)

**Comment by lucduron** [comment]
Thank you for reporting this issue.
I already had in mind some improvements for the **Vertical Cross-Section Viewer** and add some corrections in my last commit 3bf29da. In particular, there was no **temporal slider**, so I added one (this slider ignores any previous temporal selection, such as the `Select Time` operator, to be able to visualize all frames).

However I do not undestand how the version of Telemac can change the behaviour of PyTelTools (I checked the Serafin parsers on multiple files, even very old ones, without problems).
I think it is just a confusion because there was no information about the current time selection.
Could you try again with your Serafin files and tell me if it is working properly now. If it is still not the case, I would require your Serafin files (or a subset of them, only somes frames) to check.

**Comment by jamaa** [comment]
Thanks for the fix. It's working as expected now. As you said, it was probably a confusion about the time frame being diplayed (I did have a Select Last Frame node, though).

**Comment by lucduron** [comment]
Thank you for having tried again.
